# Generated by Django 3.0 on 2019-12-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imc.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Imc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classificacao', models.CharField(choices=[('PP', 'Muito abaixo do peso'), ('P', 'Abaixo do peso'), ('M', 'Peso normal'), ('G', 'Obesidade'), ('GG', 'Acima do peso'), ('XG', 'Obesidade II (severa)'), ('XGG', 'Obesidade III (mórbida)')], default='M', max_length=25)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imc.Profile')),
            ],
        ),
    ]
