# Generated by Django 3.0 on 2019-12-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0002_auto_20191218_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='imc.Profile'),
        ),
    ]
