# Generated by Django 3.0 on 2019-12-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0004_auto_20191218_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imc.Profile', unique=True),
        ),
    ]
