# Generated by Django 3.0 on 2019-12-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imc', '0006_auto_20191223_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imc', to='imc.Profile'),
        ),
    ]
